name: Test and Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: [push, pull_request]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run security scan
        run: npx audit-ci --config .audit-ci.json

  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Utiliza 2 instancias paralelas
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Verify Vite Installation
        run: pnpm list vite

      - name: Run Unit Tests
        run: pnpm test
        env:
          CI: true

      - name: Run ESLint
        run: |
          npx eslint . --ignore-pattern 'dist' --ignore-pattern 'coverage' --ignore-pattern 'cypress/support/component.js' --max-warnings 0
          if [ $? -eq 0 ]; then
            echo "✅ No linting errors found."
          else
            echo "❌ Linting errors detected."
            exit 1
          fi

      - name: Run format
        run: pnpm run format

      - name: Configure git
        run: |
          git config --global user.name "jorgeixco"
          git config --global user.email "jorgedavid.diaz@ixcomercio.com"
          git config --global user.password ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Check for changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Apply formatting changes"

      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Start application
        run: pnpm start &
        env:
          CI: true

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm run dev
          wait-on: 'http://localhost:5173'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: cypress-run

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install dependencies
        run: pnpm install

      - name: Build Project Artifacts
        run: pnpm run build

      - name: Vercel Build
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
