name: Test and Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Utiliza 2 instancias paralelas
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set up pnpm
        run: |
          export SHELL=$(which bash)
          pnpm setup
          echo "::add-path::$(pnpm config get prefix)/bin"
        shell: bash

      - name: Install dependencies
        run: pnpm install

      - name: Start application
        run: pnpm start &
        env:
          CI: true

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm start
          wait-on: 'http://localhost:5173'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: cypress-run

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set up pnpm
        run: |
          export SHELL=$(which bash)
          pnpm setup
          echo "::add-path::$(pnpm config get prefix)/bin"
        shell: bash

      - name: Install Vercel CLI
        run: pnpm add -g vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: pnpm run build

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
